BG_COLOR_HEX = '#faf3e3'
BG_COLOR_RGB = (250, 243, 227)

FONT_TYPE = 'Futura'
FONT_ATTRIBUTE = 'bold'

TITLE_SIZE = 40
TITLE_COLOR = '#1a4d2e'

PREVIEW_SIZE = 24
PREVIEW_COLOR = '#000000'

INFO_SIZE = 12
INFO_COLOR = '#ff9f29'

TITLE_FONT = (FONT_TYPE,TITLE_SIZE,FONT_ATTRIBUTE)
PREVIEW_FONT = (FONT_TYPE,PREVIEW_SIZE)
INFO_FONT = (FONT_TYPE,INFO_SIZE)